apiVersion: v1
kind: Template
labels:
  template: mongodb-database-seed
metadata:
  annotations:
    description: Seeds a Mongodb Database
    iconClass: icon-mongodb
    tags: mongodb
  name: mongodb-database-seed
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${SEED_CONFIGMAP}
  data:
    assets.json: |-
      [
          {
              "name": "Chemical Pump LX-222",
              "location": "Boiler room",
              "topic": "/sf/boiler/pump-lx222",
              "center_latitude": "37.784172",
              "center_longitude": "-122.401558",
              "geofence_radius": "4.4",
              "picture": "Chemical-Pump.jpg"
          },
          {
              "name": "Blow down separator valve VL-1",
              "location": "Boiler room",
              "topic": "/sf/boiler/separator-vl-1",
              "center_latitude": "37.784160",
              "center_longitude": "-122.401562",
              "geofence_radius": "1.0",
              "picture": "Blowdown-Valve.jpg"
          },
          {
              "name": "Surface blow down controller",
              "location": "Boiler room",
              "topic": "/sf/boiler/controller",
              "center_latitude": "37.784160",
              "center_longitude": "-122.401562",
              "geofence_radius": "1.0",
              "picture": "Blowdown-Controller.jpg"
          },
          {
              "name": "Condensate duplex pump",
              "location": "Boiler room",
              "topic": "/sf/boiler/cond-pump",
              "center_latitude": "37.784158",
              "center_longitude": "-122.401558",
              "geofence_radius": "4.4",
              "picture": "Condensate-Pump.jpg"
          },
          {
              "name": "Robotic arm joint RT-011",
              "location": "Assembly section",
              "topic": "/sf/assembly/robotic-joint",
              "center_latitude": "37.784262",
              "center_longitude": "-122.401550",
              "geofence_radius": "1.0",
              "picture": "Robotic-Arm.jpg"
          },
          {
              "name": "Teledyne DALSA Camera",
              "location": "Assembly section",
              "topic": "/sf/assembly/camera",
              "center_latitude": "37.784264",
              "center_longitude": "-122.401550",
              "geofence_radius": "1.0",
              "picture": "Teledyne-Dalsa.jpg"
          },
          {
              "name": "Lighting control unit RT-SD-1000",
              "location": "Warehouse",
              "topic": "/sf/warehouse/lighting-control",
              "center_latitude": "37.784270",
              "center_longitude": "-122.401540",
              "geofence_radius": "3.5",
              "picture": "Lighting-Control.JPG"
          },
          {
              "name": "DIN Rail power supply 240-24",
              "location": "Warehouse",
              "topic": "/sf/warehouse/power-supply",
              "center_latitude": "37.784271",
              "center_longitude": "-122.401542",
              "geofence_radius": "1.0",
              "picture": "DIN-Rail.jpg"
          }
      ]
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${APPLICATION_NAME}-${RANDOM_VALUE}
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - name: ${APPLICATION_NAME}
          image: ${IMAGE}
          command:
            - "/bin/bash"
            - "-c"
            - >
              mongoimport --db $MONGODB_DATABASE --collection ${ASSET_COLLECTION} --drop --file /etc/mongodb-seed/assets.json --jsonArray --host $MONGODB_SERVICE -u $MONGODB_USER -p $MONGODB_PASSWORD
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_SERVICE
              value: ${DATABASE_SERVICE_NAME}
          volumeMounts:
            - name: seed-volume
              mountPath: /etc/mongodb-seed
        initContainers:
        - name: ${APPLICATION_NAME}-init
          image: ${IMAGE}
          command: ['/bin/bash',  '-c', 'until mongo $MONGODB_SERVICE:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD --eval="quit()" < /dev/null; do echo Waiting for Mongodb Service; sleep 2; done;']
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: ${DATABASE_SERVICE_NAME}
            - name: MONGODB_SERVICE
              value: ${DATABASE_SERVICE_NAME}
        restartPolicy: OnFailure
        volumes:
          - name: seed-volume
            configMap:
              name: "${SEED_CONFIGMAP}"     
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: mongodb-database-seed
- description: Image name for the job
  name: IMAGE
  required: true
  value: registry.access.redhat.com/rhscl/mongodb-32-rhel7
- description: Random value for the job.
  displayName: Random Value
  from: '[a-z0-9]{5}'
  generate: expression
  name: RANDOM_VALUE
  required: true
- description: Mongodb Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: mongodb
- description: ConfigMap Seed
  name: SEED_CONFIGMAP
  required: true
  value: mongodb-seed
- description: MongoDb Asset Collection
  name: ASSET_COLLECTION
  required: true
  value: assets
