apiVersion: v1
kind: Template
labels:
  template: software-sensor-deployment
metadata:
  annotations:
    description: Deploys the Software Sensor Image
    iconClass: icon-java
    tags: java
  name: software-sensor-deployment
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Software Sensor Port.
    labels:
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      application: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
      deploymentConfig: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 0
    selector:
      application: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          - name: MQTT_URL
            value: tcp://${MQTT_APPLICATION_SERVICE}:1883
          - name: MQTT_USERNAME
            value: ${MQTT_USERNAME}
          - name: MQTT_PASSWORD
            value: ${MQTT_PASSWORD}
          - name: MQTT_TOPIC
            value: ${MQTT_TOPIC}
          - name: MQTT_CLIENTID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: ''
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: software-sensor
- description: The name for the AMQ Broker Service.
  name: MQTT_APPLICATION_SERVICE
  required: true
- description: User name for standard broker user.  It is required for connecting to the broker.  If left empty, it will be generated.
  displayName: A-MQ Username
  name: MQTT_USERNAME
- description: Password for standard broker user.  It is required for connecting to the broker.  If left empty, it will be generated.
  displayName: A-MQ Password
  required: true
  name: MQTT_PASSWORD
- description: MQTT Topic.
  name: MQTT_TOPIC
  value: proxsensor01
  required: true