spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVICE_HOST}:${MONGODB_SERVICE_PORT}/${MONGODB_DATABASE}

  activemq:
    broker-url: tcp://${BROKER_AMQ_SERVICE_HOST}:${BROKER_AMQ_SERVICE_PORT}
    
openwhisk:
  apiHost: "http://nginx.openwhisk.svc.cluster.local"
  namespaceEndpoint: "/api/v1/namespaces"