spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
openwhisk:
  apiHost: "http://nginx.openwhisk.svc.cluster.local"
  namespaceEndpoint: "/api/v1/namespaces"