spring:
  datasource:
    url: "jdbc:h2:mem:triggerdata;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:
    driver-class-name: org.h2.Driver

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
openwhisk:
  apiHost: "http://nginx.openwhisk.svc.cluster.local"
  namespaceEndpoint: "/api/v1/namespaces"