---
  openshift_cluster_content:
  - object: projectrequest
    content:
    - name: iot-serverless-project
      template: "https://raw.githubusercontent.com/redhat-cop/cluster-lifecycle/master/files/projectrequest/template.yml"
      template_action: create
      params: "{{ inventory_dir }}/../params/iot-serverless-project"
  - object: deployments
    content:
    - name: "deploy-amq"
      template: "openshift//amq63-persistent"
      params: "{{ inventory_dir }}/../params/amq"
      namespace: iot-serverless
    - name: "deploy-mqtt-provider"
      template: "{{ inventory_dir }}/../templates/deployment.yml"
      params: "{{ inventory_dir }}/../params/deployment"
      namespace: iot-serverless
  - object: builds
    content:
      - name: "build-mqtt-provider"
        template: "{{ inventory_dir }}/../templates/build.yml"
        params: "{{ inventory_dir }}/../params/build"
        namespace: iot-serverless
    